//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Apartment
{
    public string apartmentNr { get; set; }

    public virtual BookingList BookingList { get; set; }
}

public partial class BookingList
{
    public string apartmentNr { get; set; }
    public string bookedDate { get; set; }
    public string bookedLaundryTime { get; set; }

    public virtual Apartment Apartment { get; set; }
    public virtual LaundryTime LaundryTime { get; set; }
}

public partial class LaundryTime
{
    public LaundryTime()
    {
        this.BookingList = new HashSet<BookingList>();
    }

    public string bookedLaundryTime { get; set; }
    public string description { get; set; }

    public virtual ICollection<BookingList> BookingList { get; set; }
}
